# This rule is not used by the project cert-validator-operator itself.
# It is provided to allow the cluster admin to help manage permissions for users.
#
# Grants full permissions ('*') over core.certwatcher.io.
# This role is intended for users authorized to modify roles and bindings within the cluster,
# enabling them to delegate specific permissions to other users or groups as needed.

apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  labels:
    app.kubernetes.io/name: cert-validator-operator
    app.kubernetes.io/managed-by: kustomize
  name: certvalidate-admin-role
rules:
- apiGroups:
  - core.certwatcher.io
  resources:
  - certvalidates
  verbs:
  - '*'
- apiGroups:
  - core.certwatcher.io
  resources:
  - certvalidates/status
  verbs:
  - get
