# This rule is not used by the project cert-validator-operator itself.
# It is provided to allow the cluster admin to help manage permissions for users.
#
# Grants permissions to create, update, and delete resources within the core.certwatcher.io.
# This role is intended for users who need to manage these resources
# but should not control RBAC or manage permissions for others.

apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  labels:
    app.kubernetes.io/name: cert-validator-operator
    app.kubernetes.io/managed-by: kustomize
  name: certvalidate-editor-role
rules:
- apiGroups:
  - core.certwatcher.io
  resources:
  - certvalidates
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - core.certwatcher.io
  resources:
  - certvalidates/status
  verbs:
  - get
